# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a97e6c7f862151c7253c762b2214634b95b9f283512b7ecf9aa041ff018a5da2fe907d04ab050427dc3ccfdf2daf0b2981c5227bc68f8cf3a05210272784956

test:
  secret_key_base: 300f7fd540f749663b1862d68ba02e94d15fe0b0160e7b91bde5689373399384a87958976c52a5a0dfa8dbb213e859a83307efa6b7d7d9b6ddfe38040e340cf7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
